### ISSUE TITLE
clearAllObjectsFromCache rmdir directory not empty

### ISSUE THREAD

**Issue by pravo-pro** [php-cache/issues#149]
Good day! I use a file cache, because RAM on such volumes will be an expensive solution.
Sometime when i change some parameters, i need to clear the entire cache 
in log i found the errror 
```
rmdir directory not empty 
#1 /vendor/league/flysystem/src/Adapter/Local.php(420): rmdir('/var/www/sitedir-...')
#2 /vendor/league/flysystem/src/Filesystem.php(251): League\\Flysystem\\Adapter\\Local->deleteDir('cache')
#3 /vendor/cache/filesystem-adapter/FilesystemCachePool.php(94): League\\Flysystem\\Filesystem->deleteDir('cache')
#4 /vendor/cache/adapter-common/AbstractCachePool.php(176): Cache\\Adapter\\Filesystem\\FilesystemCachePool->clearAllObjectsFromCache()
```
After analyzing the sources, I saw that you take the specified folder, delete all folders/files/links from it recursively, and then delete the folder itself. But during deletion, a NEW cache is created. which will not be deleted by the function earlier, and it will not be possible to delete the parent folder accordingly. Why the cache folder is recreated every time, is it possible to disable it somehow, deleting only the contents found at the time of starting the cache cleanup? or temporary disable cache while deleting(not best choise)

P.S. using laravel 8

**Comment by cryptiklemur** [comment]
Thanks for the detailed diagnosis. [`cache/filesystem-adapter` 2.0.3 clears listed files without deleting the cache directory](https://github.com/php-cache/filesystem-adapter/blob/2.0.3/FilesystemCachePool.php#L112-L121). It also has [regression coverage confirming that `clear()` keeps the same directory](https://github.com/php-cache/filesystem-adapter/blob/2.0.3/Tests/FilesystemCachePoolTest.php#L169-L179), avoiding the reported `rmdir` race. I'm closing this as resolved. If this recurs on 2.0.3, please reopen the issue with a reproducer and the Flysystem version.
